# Generated by Django 3.1.7 on 2021-04-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0003_auto_20210414_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='myuploadfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('desciption', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='desciption',
        ),
    ]
