# Generated by Django 3.1.7 on 2021-04-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0006_auto_20210415_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuploadfile',
            old_name='desciption',
            new_name='description',
        ),
    ]
