# Generated by Django 3.1.7 on 2021-04-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0007_auto_20210415_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuploadfile',
            name='file',
            field=models.FileField(upload_to='file'),
        ),
    ]
