# Generated by Django 3.1.7 on 2021-04-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0008_auto_20210415_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuploadfile',
            name='file_name',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='Enter YOUR NAME', max_length=100),
        ),
        migrations.AlterField(
            model_name='myuploadfile',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='myuploadfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
