# Generated by Django 3.1.7 on 2021-05-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0009_auto_20210417_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuploadfile',
            name='file_image',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
