# Generated by Django 3.1.7 on 2021-05-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0010_myuploadfile_imgfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuploadfile',
            name='description',
            field=models.TextField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='myuploadfile',
            name='file_name',
            field=models.TextField(default=False, max_length=50),
        ),
    ]
