# Generated by Django 3.1.7 on 2021-05-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0011_auto_20210502_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuploadfile',
            old_name='file_image',
            new_name='file_image',
        ),
    ]
