# Generated by Django 3.1.7 on 2021-05-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0012_auto_20210502_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuploadfile',
            name='file_image',
            field=models.FileField(upload_to=''),
        ),
    ]
