# Generated by Django 3.1.7 on 2021-05-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0013_auto_20210502_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('description', models.TextField(default=False, max_length=50)),
                ('file_name', models.TextField(default=False, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_image', models.FileField(upload_to='')),
            ],
        ),
    ]
